### ISSUE TITLE
Issue: Click action

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1118]
```
Action(element_id=x1I3, text=W01-377-8537), ClickAction(element_id=YNax, file_url=None, download=False)] step_id=stp_322054360133458360 step_order=0 step_retry=2 task_id=tsk_322053887687055420
2024-11-03T20:55:51.391644Z [error    ] Unexpected exception in agent_step, marking step as failed step_id=stp_322054360133458360 step_order=0 step_retry=2 task_id=tsk_322053887687055420
Traceback (most recent call last):
  File "/home/hue/Desktop/agi/agents/open-source/skyvern/skyvern/forge/agent.py", line 757, in agent_step
    results = await ActionHandler.handle_action(scraped_page, task, step, browser_state, action)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hue/Desktop/agi/agents/open-source/skyvern/skyvern/webeye/actions/handler.py", line 343, in handle_action
    LOG.info("Handling action", action)
  File "/home/hue/.cache/pypoetry/virtualenvs/skyvern-tAhOyrZQ-py3.11/lib/python3.11/site-packages/structlog/_native.py", line 136, in meth
    return self._proxy_to_logger(name, event % args, **kw)
                                       ~~~~~~^~~~~~
TypeError: not all arguments converted during string formatting
```

I tested on the following request:
```
curl 'http://localhost:8000/api/v1/tasks' -X POST -H "Content-Type: application/json" -H "x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4NzU2MjUzNTQsInN1YiI6Im9fMzIyMDQ1OTAxMTQyNjM3NjE2In0.CFUEjxXg-vAqb4JdPYy8HrI93q3f8CXs48vkvCcQV3g" --data-binary '{"title":null,"url":"https://www.finditparts.com","webhook_callback_url":null,"navigation_goal":"https://www.finditparts.com Search for the specified product id, add it to cart and then navigate to the cart page. Your goal is COMPLETE when you'\''re on the cart page and the specified product is in the cart. Do not attempt to checkout.","data_extraction_goal":"Extract all product quantity information from the cart page","proxy_location":"RESIDENTIAL","navigation_payload":"{\n  \"product_id\": \"W01-377-8537\"\n}","extracted_information_schema":null,"totp_verification_url":null,"totp_identifier":null,"error_code_mapping":null}'
```

This is on Ubuntu 24.04 LTS, and on the contributor setup running locally.

**Comment by devinat1** [comment]
It was an issue with my additions and not the original Skyvern repo
