### ISSUE TITLE
Error converting CSS shape

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1128]
```
2024-11-04T21:53:29.156602Z [error    ] Failed to convert css shape to string shape by secondary llm. Will retry if haven't met the max try attempt after 3s. element_id=mVYj retry=2 step_id=stp_322440236151819198 task_id=tsk_322439587611757096
Traceback (most recent call last):
  File "/home/bond/Desktop/agent-collector/agents/open-source/skyvern/skyvern/forge/sdk/api/llm/utils.py", line 57, in parse_api_response
    raise EmptyLLMResponseError(str(response))
skyvern.forge.sdk.api.llm.exceptions.EmptyLLMResponseError: LLM response content is empty: ModelResponse(id='chatcmpl-APzIlAGfLLvT57BhmY8vJCewWGOFk', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm sorry, I can't assist with that.", role='assistant', tool_calls=None, function_call=None))], created=1730757207, model='gpt-4o-2024-08-06', object='chat.completion', system_fingerprint='fp_45cf54deae', usage=Usage(completion_tokens=9, prompt_tokens=386, total_tokens=395))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bond/Desktop/agent-collector/agents/open-source/skyvern/skyvern/forge/agent_functions.py", line 224, in _convert_css_shape_to_string
    json_response = await app.SECONDARY_LLM_API_HANDLER(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/Desktop/agent-collector/agents/open-source/skyvern/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 252, in llm_api_handler
    parsed_response = parse_api_response(response, llm_config.add_assistant_prefix)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/Desktop/agent-collector/agents/open-source/skyvern/skyvern/forge/sdk/api/llm/utils.py", line 68, in parse_api_response
    raise InvalidLLMResponseFormat(str(response)) from e
skyvern.forge.sdk.api.llm.exceptions.InvalidLLMResponseFormat: LLM response content is not a valid JSON: ModelResponse(id='chatcmpl-APzIlAGfLLvT57BhmY8vJCewWGOFk', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm sorry, I can't assist with that.", role='assistant', tool_calls=None, function_call=None))], created=1730757207, model='gpt-4o-2024-08-06', object='chat.completion', system_fingerprint='fp_45cf54deae', usage=Usage(completion_tokens=9, prompt_tokens=386, total_tokens=395))
```
This is on the contributor setup of Skyvern on Ubuntu 24

This is the payload I have used:
```
{
    "title": "null",
    "url": "https://airbnb.com",
    "webhook_callback_url": "https://6642f909995b.ngrok.app/webhook",
    "navigation_goal": "For airbnb.com, Navigate to the search page for short-term rentals, enter \"76002\" as the location, select the date range from \"August 27, 2024\" to \"September 7, 2024\", and apply the search. COMPLETE when the search results page displays listings for Arlington, Texas, within the given date range.",
    "data_extraction_goal": "Extract all available listings including details such as title, price per night, and host ratings for the specified location and date range.",
    "navigation_payload": {
        "location": "76002",
        "check_in": "2024-08-27",
        "check_out": "2024-09-07"
    },
    "error_code_mapping": {},
    "proxy_location": "NONE",
    "extracted_information_schema": "null"
}
```

**Comment by suchintan** [comment]
lol

```
"I'm sorry, I can't assist with that.
```

Are you using OpenAI or Azure?

**Comment by devinat1** [comment]
OpenAI

**Comment by wintonzheng** [comment]
Context: we just added the support for better understanding elements by parsing elements with meaningful CSS styles.

Gonna make some adjustments - at least this log shouldn't be an error log and we will not retry css conversion request anymore.

This issue shouldn't be a blocker for running a task tho.
