### ISSUE TITLE
skyvern.forge.sdk.api.llm.exceptions.LLMProviderError

### ISSUE THREAD

**Issue by chloecd** [Skyvern-AI/skyvern#1177]
Hey Guys,

I've got an exception when I run Skyvern with docker images on Ubuntu.
There's a proxy which is help me to access the internet. I'm not sure if it's related to this error. And how I can fix it

skyvern-1     | 2024-11-12T09:02:41.831682Z [info     ] Calling LLM API                llm_key=OPENAI_GPT4O model=gpt-4o
skyvern-1     | 09:09:14 - LiteLLM:ERROR: main.py:415 - litellm.acompletion(): Exception occured - Connection error.
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
skyvern-1     |     yield
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
skyvern-1     |     resp = await self._pool.handle_async_request(req)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
skyvern-1     |     raise exc from None
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
skyvern-1     |     response = await connection.handle_async_request(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
skyvern-1     |     raise exc
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
skyvern-1     |     stream = await self._connect(request)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
skyvern-1     |     stream = await self._network_backend.connect_tcp(**kwargs)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
skyvern-1     |     return await self._backend.connect_tcp(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
skyvern-1     |     with map_exceptions(exc_map):
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
skyvern-1     |     raise to_exc(exc) from exc
skyvern-1     | httpcore.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1548, in _request
skyvern-1     |     response = await self._client.send(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
skyvern-1     |     response = await self._send_handling_auth(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
skyvern-1     |     response = await self._send_handling_redirects(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
skyvern-1     |     response = await self._send_single_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
skyvern-1     |     response = await transport.handle_async_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
skyvern-1     |     with map_httpcore_exceptions():
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
skyvern-1     |     raise mapped_exc(message) from exc
skyvern-1     | httpx.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 394, in acompletion
skyvern-1     |     response = await init_response
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1128, in acompletion
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1083, in acompletion
skyvern-1     |     headers, response = await self.make_openai_chat_completion_request(
skyvern-1     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 785, in make_openai_chat_completion_request
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 780, in make_openai_chat_completion_request
skyvern-1     |     response = await openai_aclient.chat.completions.create(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1289, in create
skyvern-1     |     return await self._post(
skyvern-1     |            ^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1816, in post
skyvern-1     |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1514, in request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1582, in _request
skyvern-1     |     raise APIConnectionError(request=request) from err
skyvern-1     | openai.APIConnectionError: Connection error.
skyvern-1     | 
skyvern-1     | 
skyvern-1     | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
skyvern-1     | LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
skyvern-1     | 
skyvern-1     | 2024-11-12T09:09:14.338880Z [error    ] LLM request failed unexpectedly llm_key=OPENAI_GPT4O
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
skyvern-1     |     yield
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
skyvern-1     |     resp = await self._pool.handle_async_request(req)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
skyvern-1     |     raise exc from None
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
skyvern-1     |     response = await connection.handle_async_request(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
skyvern-1     |     raise exc
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
skyvern-1     |     stream = await self._connect(request)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
skyvern-1     |     stream = await self._network_backend.connect_tcp(**kwargs)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
skyvern-1     |     return await self._backend.connect_tcp(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
skyvern-1     |     with map_exceptions(exc_map):
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
skyvern-1     |     raise to_exc(exc) from exc
skyvern-1     | httpcore.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1548, in _request
skyvern-1     |     response = await self._client.send(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
skyvern-1     |     response = await self._send_handling_auth(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
skyvern-1     |     response = await self._send_handling_redirects(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
skyvern-1     |     response = await self._send_single_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
skyvern-1     |     response = await transport.handle_async_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
skyvern-1     |     with map_httpcore_exceptions():
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
skyvern-1     |     raise mapped_exc(message) from exc
skyvern-1     | httpx.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 394, in acompletion
skyvern-1     |     response = await init_response
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1128, in acompletion
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1083, in acompletion
skyvern-1     |     headers, response = await self.make_openai_chat_completion_request(
skyvern-1     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 785, in make_openai_chat_completion_request
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 780, in make_openai_chat_completion_request
skyvern-1     |     response = await openai_aclient.chat.completions.create(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1289, in create
skyvern-1     |     return await self._post(
skyvern-1     |            ^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1816, in post
skyvern-1     |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1514, in request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1582, in _request
skyvern-1     |     raise APIConnectionError(request=request) from err
skyvern-1     | openai.APIConnectionError: Connection error.
skyvern-1     | 
skyvern-1     | During handling of the above exception, another exception occurred:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/app/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 213, in llm_api_handler
skyvern-1     |     response = await litellm.acompletion(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1524, in wrapper_async
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1336, in wrapper_async
skyvern-1     |     result = await original_function(*args, **kwargs)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 422, in acompletion
skyvern-1     |     raise exception_type(
skyvern-1     |           ^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8060, in exception_type
skyvern-1     |     raise e  # it's already mapped
skyvern-1     |     ^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6498, in exception_type
skyvern-1     |     raise APIConnectionError(
skyvern-1     | litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: OpenAIException - Connection error.
skyvern-1     | 2024-11-12T09:09:14.344341Z [error    ] Failed to convert css shape to string shape by secondary llm. Will retry if haven't met the max try attempt after 3s. element_id=g6qt retry=0 step_id=stp_325210390015393330 task_id=tsk_325210390015393328
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
skyvern-1     |     yield
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
skyvern-1     |     resp = await self._pool.handle_async_request(req)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
skyvern-1     |     raise exc from None
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
skyvern-1     |     response = await connection.handle_async_request(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
skyvern-1     |     raise exc
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
skyvern-1     |     stream = await self._connect(request)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
skyvern-1     |     stream = await self._network_backend.connect_tcp(**kwargs)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
skyvern-1     |     return await self._backend.connect_tcp(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
skyvern-1     |     with map_exceptions(exc_map):
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
skyvern-1     |     raise to_exc(exc) from exc
skyvern-1     | httpcore.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1548, in _request
skyvern-1     |     response = await self._client.send(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
skyvern-1     |     response = await self._send_handling_auth(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
skyvern-1     |     response = await self._send_handling_redirects(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
skyvern-1     |     response = await self._send_single_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
skyvern-1     |     response = await transport.handle_async_request(request)
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
skyvern-1     |     with map_httpcore_exceptions():
skyvern-1     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
skyvern-1     |     self.gen.throw(typ, value, traceback)
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
skyvern-1     |     raise mapped_exc(message) from exc
skyvern-1     | httpx.ConnectError: All connection attempts failed
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 394, in acompletion
skyvern-1     |     response = await init_response
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1128, in acompletion
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1083, in acompletion
skyvern-1     |     headers, response = await self.make_openai_chat_completion_request(
skyvern-1     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 785, in make_openai_chat_completion_request
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 780, in make_openai_chat_completion_request
skyvern-1     |     response = await openai_aclient.chat.completions.create(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1289, in create
skyvern-1     |     return await self._post(
skyvern-1     |            ^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1816, in post
skyvern-1     |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1514, in request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1572, in _request
skyvern-1     |     return await self._retry_request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1641, in _retry_request
skyvern-1     |     return await self._request(
skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1582, in _request
skyvern-1     |     raise APIConnectionError(request=request) from err
skyvern-1     | openai.APIConnectionError: Connection error.
skyvern-1     | 
skyvern-1     | During handling of the above exception, another exception occurred:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/app/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 213, in llm_api_handler
skyvern-1     |     response = await litellm.acompletion(
skyvern-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1524, in wrapper_async
skyvern-1     |     raise e
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1336, in wrapper_async
skyvern-1     |     result = await original_function(*args, **kwargs)
skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 422, in acompletion
skyvern-1     |     raise exception_type(
skyvern-1     |           ^^^^^^^^^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8060, in exception_type
skyvern-1     |     raise e  # it's already mapped
skyvern-1     |     ^^^^^^^
skyvern-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6498, in exception_type
skyvern-1     |     raise APIConnectionError(
skyvern-1     | litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: OpenAIException - Connection error.
skyvern-1     | 
skyvern-1     | The above exception was the direct cause of the following exception:
skyvern-1     | 
skyvern-1     | Traceback (most recent call last):
skyvern-1     |   File "/app/skyvern/forge/agent_functions.py", line 226, in _convert_css_shape_to_string
skyvern-1     |     json_response = await app.SECONDARY_LLM_API_HANDLER(
skyvern-1     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1     |   File "/app/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 233, in llm_api_handler
skyvern-1     |     raise LLMProviderError(llm_key) from e
skyvern-1     | skyvern.forge.sdk.api.llm.exceptions.LLMProviderError: Error while using LLMProvider OPENAI_GPT4O
skyvern-1     | 2024-11-12T09:09:17.391957Z [info     ] Calling LLM API                llm_key=OPENAI_GPT4O model=gpt-4o

**Comment by suchintan** [comment]
What website did you send it to? 

Does your docker container have access to the internet? 

```
skyvern-1 | litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: OpenAIException - Connection error.
```
This implies that it couldn't even establish a connection with OpenAI

**Comment by chloecd** [comment]
the test website is www.baidu.com, and when the proxy is running, I could access both google and baidu via browser. I'm wondering if set a proxy in the docker

**Comment by suchintan** [comment]
You'll definitely need to set a proxy inside Docker (if you can't access it without the proxy)

**Comment by chloecd** [comment]
I've tried install smth in Docker without proxy, and it worked. Seems it accesses to the internet well.

root@45c115451eb3:/app/skyvern/forge/sdk/routes# apt install curl -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl4
The following NEW packages will be installed:
  curl libcurl4
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 704 kB of archives.
After this operation, 1359 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libcurl4 amd64 7.88.1-10+deb12u7 [390 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 curl amd64 7.88.1-10+deb12u7 [315 kB]
Fetched 704 kB in 3s (281 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcurl4:amd64.
(Reading database ... 25489 files and directories currently installed.)
Preparing to unpack .../libcurl4_7.88.1-10+deb12u7_amd64.deb ...
Unpacking libcurl4:amd64 (7.88.1-10+deb12u7) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.88.1-10+deb12u7_amd64.deb ...
Unpacking curl (7.88.1-10+deb12u7) ...
Setting up libcurl4:amd64 (7.88.1-10+deb12u7) ...
Setting up curl (7.88.1-10+deb12u7) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
root@45c115451eb3:/app/skyvern/forge/sdk/routes#

**Comment by chloecd** [comment]
I set a proxy inside Docker now, then curl google.com and api.openai.com,
it works fine.

Besides, I tried another script inside Docker，which uses gpt-4o to describe
a small pic. It works fine as well.

Nevertheless, not working on Skyvern.

If or how I can set a global proxy in skyvern scripts?

Suchintan ***@***.***> 于2024年11月13日周三 13:42写道：
