### ISSUE TITLE
Create task Faild

### ISSUE THREAD

**Issue by Yasser-shrief** [Skyvern-AI/skyvern#1424]
![image](https://github.com/user-attachments/assets/d8c878c1-0f35-4111-85dd-d2a30c17fe21)

Unexpected Application Error!
404 Not Found 

Faild to create and run new task 

```
2024-12-23 15:44:25 skyvern-1     | 2024-12-23T07:44:25.178209Z [info     ] Creating workflow from request organization_id=o_340403700108286438 title=applyaboard
2024-12-23 15:44:25 skyvern-1     | 2024-12-23T07:44:25.228696Z [error    ] Failed to create workflow from request, deleting workflow w_340404786115001526 organization_id=o_340403700108286438
2024-12-23 15:44:25 skyvern-1     | 2024-12-23T07:44:25.239017Z [error    ] Failed to update workflow      organization_id=o_340403700108286438 workflow_permanent_id=wpid_340403922826574942
2024-12-23 15:44:25 skyvern-1     | Traceback (most recent call last):
2024-12-23 15:44:25 skyvern-1     |   File "/app/skyvern/forge/sdk/routes/agent_protocol.py", line 746, in update_workflow
2024-12-23 15:44:25 skyvern-1     |     return await app.WORKFLOW_SERVICE.create_workflow_from_request(
2024-12-23 15:44:25 skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/app/skyvern/forge/sdk/workflow/service.py", line 1263, in create_workflow_from_request
2024-12-23 15:44:25 skyvern-1     |     raise e
2024-12-23 15:44:25 skyvern-1     |   File "/app/skyvern/forge/sdk/workflow/service.py", line 1186, in create_workflow_from_request
2024-12-23 15:44:25 skyvern-1     |     parameters[parameter.key] = await self.create_workflow_parameter(
2024-12-23 15:44:25 skyvern-1     |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/app/skyvern/forge/sdk/workflow/service.py", line 584, in create_workflow_parameter
2024-12-23 15:44:25 skyvern-1     |     return await app.DATABASE.create_workflow_parameter(
2024-12-23 15:44:25 skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/app/skyvern/forge/sdk/db/client.py", line 1255, in create_workflow_parameter
2024-12-23 15:44:25 skyvern-1     |     json.dumps(default_value)
2024-12-23 15:44:25 skyvern-1     |   File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
2024-12-23 15:44:25 skyvern-1     |     return _default_encoder.encode(obj)
2024-12-23 15:44:25 skyvern-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
2024-12-23 15:44:25 skyvern-1     |     chunks = self.iterencode(o, _one_shot=True)
2024-12-23 15:44:25 skyvern-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
2024-12-23 15:44:25 skyvern-1     |     return _iterencode(o, 0)
2024-12-23 15:44:25 skyvern-1     |            ^^^^^^^^^^^^^^^^^
2024-12-23 15:44:25 skyvern-1     |   File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
2024-12-23 15:44:25 skyvern-1     |     raise TypeError(f'Object of type {o.__class__.__name__} '
2024-12-23 15:44:25 skyvern-1     | TypeError: Object of type date is not JSON serializable
```

**Comment by Yasser-shrief** [comment]
The same issue on skyvern cloud 
![image](https://github.com/user-attachments/assets/ac3dd695-c473-481a-b279-97e65845f234)

**Comment by rublev** [comment]
getting the same locally

**Comment by suchintan** [comment]
@Yasser-shrief @rublev are you still seeing this issue?

**Comment by deveshruttala-edu** [comment]
👋 Hey there! This looks like something Hyperbrowser could assist with. We're building an AI-native browser that automates workflows, integrates smart tools, and enhances productivity directly inside the browser. If you're tackling tasks like this often, Hyperbrowser might be just what you need.

🚀 Learn more and try it out: https://www.hyperbrowser.ai/
We’d love your feedback!

**Comment by deveshruttala-edu** [comment]
👋 Hey there! This looks like something Hyperbrowser could assist with. We're building an AI-native browser that automates workflows, integrates smart tools, and enhances productivity directly inside the browser. If you're tackling tasks like this often, Hyperbrowser might be just what you need.

🚀 Learn more and try it out: https://www.hyperbrowser.ai/
We’d love your feedback!
