### ISSUE TITLE
Error " Error while using LLMProvider OPENAI_GPT4V"

### ISSUE THREAD

**Issue by MatthD** [Skyvern-AI/skyvern#278]
Hello !

Thanks for this beauty project,

Just trying to use it to learn, I am failing into this issue:

```bash
  2024-05-08T08:39:58.010781Z [error    ] Unexpected exception in agent_step, marking step as failed step_id=stp_255440540893745180 step_order=2 step_retry=5 task_id=tsk_255439643245582210
Traceback (most recent call last):
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/main.py", line 319, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 478, in acompletion
    raise e
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 463, in acompletion
    response = await openai_aclient.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1291, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1578, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1339, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1429, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 203160 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dieudonn/Dev/Skyvern/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 179, in llm_api_handler
    response = await litellm.acompletion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 3609, in wrapper_async
    raise e
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 3441, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/main.py", line 340, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8965, in exception_type
    raise e
  File "/Users/dieudonn/Library/Caches/pypoetry/virtualenvs/skyvern-oacw3Bls-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7682, in exception_type
    raise ContextWindowExceededError(
litellm.exceptions.ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 203160 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dieudonn/Dev/Skyvern/skyvern/forge/agent.py", line 371, in agent_step
    json_response = await app.LLM_API_HANDLER(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dieudonn/Dev/Skyvern/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 185, in llm_api_handler
    raise LLMProviderError(llm_key) from e
skyvern.forge.sdk.api.llm.exceptions.LLMProviderError: Error while using LLMProvider OPENAI_GPT4V
2024-05-08T08:39:58.016473Z [info     ] Updating step in db            diff={'status': {'old': <StepStatus.running: 'running'>, 'new': <StepStatus.failed: 'failed'>}, 'output': {'old': None, 'new': AgentStepOutput({'action_results': [], 'actions_and_results': [], 'errors': []})}} step_id=stp_255440540893745180 task_id=tsk_255439643245582210
2024-05-08T08:39:58.032515Z [warning  ] Step failed after max retries, marking task as failed max_retries=5 step_id=stp_255440540893745180 step_order=2 step_retry=5 task_id=tsk_255439643245582210
2024-05-08T08:39:58.032662Z [info     ] Updating task in db            diff={'status': {'old': <TaskStatus.running: 'running'>, 'new': <TaskStatus.failed: 'failed'>}, 'failure_reason': {'old': None, 'new': 'Max retries per step (5) exceeded'}} task_id=tsk_255439643245582210
2024-05-08T08:39:58.061793Z [info     ] Page is fully loaded, agent is about to take screenshots
2024-05-08T08:39:59.161528Z [info     ] Cleaning up for task
2024-05-08T08:39:59.161572Z [info     ] Closing browser state
2024-05-08T08:39:59.161584Z [info     ] Closing browser context and its pages
2024-05-08T08:40:00.246049Z [info     ] Main browser context and all its pages are closed
2024-05-08T08:40:00.246104Z [info     ] Stopping playwright
2024-05-08T08:40:00.254179Z [info     ] Playwright is stopped
2024-05-08T08:40:00.254229Z [info     ] Task is cleaned up
2024-05-08T08:40:00.303678Z [info     ] S3 upload tasks for task_id=tsk_255439643245582210 completed in 0.02s duration=0.015383720397949219 task_id=tsk_255439643245582210
2024-05-08T08:40:00.303845Z [warning  ] Task has no webhook callback url. Not sending task response task_id=tsk_255439643245582210
```

**I did setup openAI only** Tried both model but lead to same issue. Is it possible to truncate what is send instead of failing ?

**Comment by suchintan** [comment]
What website are you running it on? There's a known issue (https://github.com/Skyvern-AI/skyvern/issues/49) Where if you run Skyvern on a website with a LOT of interactable elements, you run into OpenAI token limits :(

**Comment by suchintan** [comment]
I suspect you hit the same issue here:

litellm.exceptions.ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 203160 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

**Comment by suchintan** [comment]
We're working on changes to compress our prompt which should help in cases like this!
