### ISSUE TITLE
Exit gracefully

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#383]
On certain occasions, skyvern gets stuck in a loop where it takes a screenshot or constructs a tree from the same exact page, not knowing what to do. This is especially true for 404 sites.
In this scenario, I would like to press Ctrl + C to exit out of the skyvern script gracefully, wherein it doesn't stop the server but recovers in a default state (waiting for a curl request).
Here is the output I am getting upon ctrl + C:
```
4, in send_no_reply
    self._connection.wrap_api_call_sync(
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 508, in wrap_api_call_sync
    return cb()
           ^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 75, in <lambda>
    lambda: self._connection._send_message_to_server(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 360, in _send_message_to_server
    self._transport.send(message)
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_transport.py", line 178, in send
    self._output.write(
  File "/usr/lib/python3.11/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x7b8567d72f60>; the handler is closed
2024-05-28T17:55:40.387018Z [error    ] Failed to take screenshot before sending task response step_id=stp_263005482589778254 task_id=tsk_263004907064160362
Traceback (most recent call last):
  File "/home/bond/Desktop/darkpatterncombined/agents/skyvern/skyvern/webeye/browser_factory.py", line 237, in take_screenshot_from_page
    await page.wait_for_load_state(timeout=SettingsManager.get_settings().BROWSER_LOADING_TIMEOUT_MS)
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 9382, in wait_for_load_state
    await self._impl_obj.wait_for_load_state(state=state, timeout=timeout)
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_page.py", line 500, in wait_for_load_state
    return await self._main_frame.wait_for_load_state(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 247, in wait_for_load_state
    return await self._wait_for_load_state_impl(state, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 258, in _wait_for_load_state_impl
    waiter = self._setup_navigation_waiter("wait_for_load_state", timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 155, in _setup_navigation_waiter
    waiter = Waiter(self._page, f"frame.{wait_name}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_waiter.py", line 36, in __init__
    self._wait_for_event_info_before(self._wait_id, event)
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_waiter.py", line 39, in _wait_for_event_info_before
    self._channel.send_no_reply(
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 74, in send_no_reply
    self._connection.wrap_api_call_sync(
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 508, in wrap_api_call_sync
    return cb()
           ^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 75, in <lambda>
    lambda: self._connection._send_message_to_server(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 360, in _send_message_to_server
    self._transport.send(message)
  File "/home/bond/.cache/pypoetry/virtualenvs/skyvern-0Io2OvKr-py3.11/lib/python3.11/site-packages/playwright/_impl/_transport.py", line 178, in send
    self._output.write(
  File "/usr/lib/python3.11/asyncio/streams.py", line 346, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x7b8567d72f60>; the handler is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bond/Desktop/darkpatterncombined/agents/skyvern/skyvern/forge/agent.py", line 929, in send_task_response
    screenshot = await browser_state.take_screenshot(full_page=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/Desktop/darkpatterncombined/agents/skyvern/skyvern/webeye/browser_factory.py", line 273, in take_screenshot
    return await self.take_screenshot_from_page(self.page, full_page, file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bond/Desktop/darkpatterncombined/agents/skyvern/skyvern/webeye/browser_factory.py", line 266, in take_screenshot_from_page
    raise FailedToTakeScreenshot(error_message=str(e)) from e
skyvern.exceptions.FailedToTakeScreenshot: Failed to take screenshot. Error message: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x7b8567d72f60>; the handler is closed
2024-05-28T17:55:40.387870Z [info     ] Cleaning up for task          
2024-05-28T17:55:40.387911Z [info     ] Closing browser state         
2024-05-28T17:55:40.387936Z [info     ] Closing browser context and its pages
Future exception was never retrieved
future: <Future finished exception=Exception('Connection closed while reading from the driver')>
Exception: Connection closed while reading from the driver
INFO:     Stopping reloader process [75985]
(darkpatterncombined) bond@bond-Blade:~/Desktop/darkpatterncombined/agents/skyvern$ 
```

**Comment by suchintan** [comment]
@devinat1 There are 2 things you can do to solve this problem:

1. You can change `MAX_STEPS_PER_RUN` to a smaller number in your .env file (or variables in docker-compose.yml) to a smaller number than 75 forcing it to terminate after say 10 steps
2. You can add termination clauses in the prompt itself ("Terminate if you encounter xxx state or you leave yyy website url") which will halt execution and send a terminate webhook
