### ISSUE TITLE
Issue with database

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#678]
Upon a fresh run through, am getting:
```
Traceback (most recent call last):
  File "/home/vagrant/agent-collector/agents/open-source/skyvern/skyvern.py", line 184, in <module>
    PayloadGenerator(site, task, real_site)
  File "/home/vagrant/agent-collector/agents/open-source/skyvern/skyvern.py", line 58, in __init__
    res = self.send_request(payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/agent-collector/agents/open-source/skyvern/skyvern.py", line 140, in send_request
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/dark/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/dark/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/dark/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/dark/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/dark/lib/python3.11/site-packages/requests/adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/tasks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7160b8d490>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by suchintan** [comment]
@devinat1 are you using the Docker setup or the contributor setup?

**Comment by devinat1** [comment]
@suchintan Contributor setup (./setup.sh) which includes docker.
The same issue occurred on both mac and ubuntu

**Comment by suchintan** [comment]
oh interesting. you're currently not using the docker setup -- and doing the contributor setup instead

Let's assume you're running on a mac -- can you check two things:
1. Do you have postgres running via Docker?
2. Do you have postgres running via brew?

I suspect you might have both running (which always causes issues)

**Comment by devinat1** [comment]
@suchintan postgres running via Docker
If by brew you mean homebrew, no, since I am running on Ubuntu which doesn't have it.
